import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

// Import-boundary enforcement for the dependency graph defined in
// docs/architecture/monorepo_structure.md. A package may only import the
// @strengthsync/* workspaces listed as `allowed` for its directory.
const ALL_WORKSPACES = [
  '@strengthsync/ui',
  '@strengthsync/api',
  '@strengthsync/api-contract',
]

const BOUNDARY_MESSAGE =
  'Import-boundary violation: see the dependency graph in docs/architecture/monorepo_structure.md.'

const boundary = (files, allowed, extraBanned = []) => {
  const banned = ALL_WORKSPACES.filter((name) => !allowed.includes(name)).flatMap(
    (name) => [name, `${name}/*`],
  )
  return {
    files,
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: banned, message: BOUNDARY_MESSAGE },
            ...(extraBanned.length > 0 ? [{ group: extraBanned, message: BOUNDARY_MESSAGE }] : []),
          ],
        },
      ],
    },
  }
}

export default defineConfig([
  globalIgnores([
    '**/dist/**',
    '**/coverage/**',
    '**/.wrangler/**',
    'docs/**',
    // Auto-generated by `wrangler types`; editor-owned, not linted.
    '**/worker-configuration.d.ts',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    rules: {
      complexity: ['error', 10],
      'max-depth': ['error', 5],
      'max-lines-per-function': ['error', { max: 90, skipBlankLines: true, skipComments: true }],
      'max-params': ['error', 5],
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        // Allow the `const { dropped: _, ...kept } = row` omit idiom used by
        // persistence mappers.
        { ignoreRestSiblings: true, argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    files: ['apps/ui/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended, reactRefresh.configs.vite],
    languageOptions: { globals: globals.browser },
  },
  {
    // Ported shadcn/ui primitives are a component library, not fast-refresh
    // route modules: they legitimately co-export variant helpers.
    files: ['apps/ui/src/shadcn/**/*.{ts,tsx}'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  // packages/api-contract imports nothing from other workspaces.
  // The generated declaration file is auto-generated and can be large.
  {
    files: ['packages/api-contract/openapi.d.ts'],
    rules: { 'max-lines': 'off', 'max-lines-per-function': 'off' },
  },
  boundary(['packages/api-contract/**/*.ts'], []),
  // apps/ui only knows HTTP contracts; never db or agent.
  boundary(['apps/ui/**/*.{ts,tsx}'], ['@strengthsync/api-contract']),
  // apps/api owns domain + db as internal folders now, not workspace
  // packages; nothing outside apps/api can reach them (no other workspace
  // depends on @strengthsync/api).
  boundary(['apps/api/**/*.ts'], []),
  // apps/api/src/domain stays pure (zod only): no workspace packages, and no
  // reaching into sibling server folders. Declared after the apps/api
  // boundary above so it wins for files under this narrower glob.
  boundary(
    ['apps/api/src/domain/**/*.ts'],
    [],
    ['**/db/**', '**/routes/**', '**/workflows/**', '**/agent/**'],
  ),
  // apps/api/src/db may use domain, but never reaches into HTTP/workflow/
  // agent code. Declared after the apps/api boundary above so it wins for
  // files under this narrower glob.
  boundary(
    ['apps/api/src/db/**/*.ts'],
    [],
    ['**/routes/**', '**/workflows/**', '**/agent/**'],
  ),
])
