import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';
import jsonc from 'eslint-plugin-jsonc';
import { defineConfig, globalIgnores } from 'eslint/config';

// Import-boundary enforcement for the dependency graph
//  A package may only import the @strengthsync/* workspaces listed as `allowed` for its directory.
const ALL_WORKSPACES = ['@strengthsync/client', '@strengthsync/server'];

const BOUNDARY_MESSAGE = 'Import-boundary violation';

const boundary = (files, allowed, extraBanned = []) => {
  const banned = ALL_WORKSPACES.filter((name) => !allowed.includes(name)).flatMap((name) => [
    name,
    `${name}/*`,
  ]);
  return {
    files,
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: banned, message: BOUNDARY_MESSAGE },
            ...(extraBanned.length > 0 ? [{ group: extraBanned, message: BOUNDARY_MESSAGE }] : []),
          ],
        },
      ],
    },
  };
};

export default defineConfig([
  globalIgnores([
    '**/dist/**',
    '**/coverage/**',
    '**/.wrangler/**',
    'docs/**',
    // Auto-generated by `wrangler types`; editor-owned, not linted.
    '**/worker-configuration.d.ts',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    rules: {
      complexity: ['error', 10],
      'max-depth': ['error', 5],
      'max-lines-per-function': ['error', { max: 90, skipBlankLines: true, skipComments: true }],
      'max-params': ['error', 5],
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        // Allow the `const { dropped: _, ...kept } = row` omit idiom used by
        // persistence mappers.
        { ignoreRestSiblings: true, argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    files: ['client/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended, reactRefresh.configs.vite],
    languageOptions: { globals: globals.browser },
  },
  {
    // Ported shadcn/ui primitives are a component library, not fast-refresh
    // route modules: they legitimately co-export variant helpers.
    files: ['client/src/shadcn/**/*.{ts,tsx}'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  // Generated from server/openapi.json by `pnpm gen:openapi`; large by nature.
  {
    files: ['client/src/api/openapi.d.ts'],
    rules: { 'max-lines': 'off', 'max-lines-per-function': 'off' },
  },
  // client owns its generated contract types locally, so it depends on no
  // workspace package at all.
  boundary(['client/**/*.{ts,tsx}'], []),
  // server owns domain + db as internal folders now, not workspace
  // packages; nothing outside server can reach them (no other workspace
  // depends on @strengthsync/server).
  boundary(['server/**/*.ts'], []),
  // server/src/domain stays pure (zod only): no workspace packages, and no
  // reaching into sibling server folders. Declared after the server
  // boundary above so it wins for files under this narrower glob.
  boundary(
    ['server/src/domain/**/*.ts'],
    [],
    ['**/db/**', '**/routes/**', '**/workflows/**', '**/agent/**'],
  ),
  // server/src/db may use domain, but never reaches into HTTP/workflow/
  // agent code. Declared after the server boundary above so it wins for
  // files under this narrower glob.
  boundary(['server/src/db/**/*.ts'], [], ['**/routes/**', '**/workflows/**', '**/agent/**']),
  // `.json` is strict RFC 8259 with no exceptions: the `jsonc/json` language
  // rejects comments and trailing commas at parse time, so this needs no rule
  // list. A file that wants comments says so in its extension — turbo.jsonc
  // and server/wrangler.jsonc do. tsconfig.json is the one file that cannot
  // (tsc resolves that name only), so its reasoning lives next to the code it
  // describes instead. no-dupe-keys is the one thing neither language catches:
  // a repeated key is valid syntax that silently drops a value.
  {
    files: ['**/*.json'],
    plugins: { jsonc },
    language: 'jsonc/json',
    rules: { 'jsonc/no-dupe-keys': 'error' },
  },
  {
    files: ['**/*.jsonc'],
    plugins: { jsonc },
    language: 'jsonc/jsonc',
    rules: { 'jsonc/no-dupe-keys': 'error' },
  },
]);
