packages:
  - apps/*
  - services/*

allowBuilds:
  "@swc/core": true
  autoevals: true
  better-sqlite3: true
  braintrust: true
  esbuild: true
  lefthook: true
  protobufjs: true
  sharp: true
  workerd: true
