/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the signed-in athlete and all of their training data */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account and training data deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description An upstream provider refused or was unreachable */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in client */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientResponse"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the signed-in client's settings */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateClient"];
                };
            };
            responses: {
                /** @description The updated client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in client's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profile found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientProfileResponse"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        /** Create or replace the signed-in client's profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateClientProfile"];
                };
            };
            responses: {
                /** @description Profile saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientProfileResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save the signed-in client's onboarding answers as their coaching profile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["OnboardingAnswers"];
                };
            };
            responses: {
                /** @description Profile saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientProfileResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/plans/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in client's active plan */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanResponse"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the signed-in client's plans by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    planId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate and activate the signed-in client's first plan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan generated and activated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeneratePlanResponse"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Conflicts with existing state */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/weeks/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in client's current in-flight week */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Week found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeekResponse"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in client's weeks */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["WeekStatus"];
                    planId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Weeks found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeekListResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/weeks/{weekId}/days/{dayIndex}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a day's exercise logs and mark the day completed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    weekId: string;
                    dayIndex: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveDayLog"];
                };
            };
            responses: {
                /** @description Day saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeekResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/weeks/{weekId}/days/{dayIndex}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Low-level day log patch (tests/tools) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    weekId: string;
                    dayIndex: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateDayLog"];
                };
            };
            responses: {
                /** @description Day patched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeekResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/wf/complete-week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete the signed-in client's week (starts the Cloudflare Workflow) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Week completed workflow started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompleteWeekStarted"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            ok: boolean;
        };
        ApiError: {
            error: {
                code: string;
                message: string;
            };
        };
        ClientResponse: {
            client: components["schemas"]["Client"];
        };
        Client: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            coach_id: string;
            display_name: string;
            /** @enum {string} */
            status: "active" | "archived";
            /** @enum {string} */
            unit_preference: "imperial" | "metric";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateClient: {
            /** @enum {string} */
            unit_preference: "imperial" | "metric";
        };
        ClientProfileResponse: {
            profile: components["schemas"]["ClientProfile"];
        };
        ClientProfile: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            client_id: string;
            /** Format: date */
            snapshot_date: string;
            sex: string | null;
            age: number | null;
            height_in: number | null;
            goals: {
                [key: string]: unknown;
            };
            body_composition: {
                [key: string]: unknown;
            };
            strength_loads: {
                [key: string]: unknown;
            };
            nutrition: {
                [key: string]: unknown;
            } | null;
            activities: {
                [key: string]: unknown;
            } | null;
            schedule_preferences: {
                [key: string]: unknown;
            } | null;
            notes: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        UpdateClientProfile: {
            /** Format: date */
            snapshot_date: string;
            sex: string | null;
            age: number | null;
            height_in: number | null;
            goals: {
                [key: string]: unknown;
            };
            body_composition: {
                [key: string]: unknown;
            };
            strength_loads: {
                [key: string]: unknown;
            };
            nutrition: {
                [key: string]: unknown;
            } | null;
            activities: {
                [key: string]: unknown;
            } | null;
            schedule_preferences: {
                [key: string]: unknown;
            } | null;
            notes: string | null;
        };
        OnboardingAnswers: {
            /** @enum {string} */
            sex: "male" | "female" | "other";
            age: number;
            height_in: number;
            weight_lb: number;
            body_fat_percent?: number;
            /** @enum {string} */
            goal: "lose_fat" | "build_muscle" | "get_stronger";
            /** Format: date */
            target_date?: string;
            target_weight_lb?: number;
            note?: string;
            /** @enum {string} */
            experience: "beginner" | "intermediate" | "advanced";
            squat_lb?: number;
            bench_press_lb?: number;
            deadlift_lb?: number;
            overhead_press_lb?: number;
            days_per_week: number;
            rest_day: number;
            activities?: {
                name: string;
                sessions_per_week: number;
                note?: string;
            }[];
            /** @enum {string} */
            daily_activity_level?: "sedentary" | "lightly_active" | "moderately_active" | "very_active";
            /** @enum {string} */
            eating_phase?: "deficit" | "maintenance" | "surplus";
            protein_target_g?: number;
            injury_note?: string;
        };
        PlanResponse: {
            plan: components["schemas"]["Plan"];
        };
        Plan: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            client_id: string;
            label: string;
            /** @enum {string} */
            status: "draft" | "active" | "archived";
            total_weeks: number;
            week_template: components["schemas"]["PlanDay"][];
            rationale: string | null;
            /** Format: date-time */
            activated_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlanDay: {
            day_index: number;
            type: components["schemas"]["DayType"];
            notes: string | null;
            exercises: components["schemas"]["PlannedExercise"][];
        };
        /** @enum {string} */
        DayType: "upper_body" | "leg_day" | "full_body" | "rest" | "activity" | "cardio";
        PlannedExercise: {
            exercise_key: string;
            name: string;
            series: number;
            reps: number;
            rest_time_sec: number;
            weight_lb: number | null;
            notes: string | null;
        };
        GeneratePlanResponse: {
            plan: components["schemas"]["Plan"];
            first_week: components["schemas"]["Week"];
        };
        Week: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            client_id: string;
            /** Format: uuid */
            plan_id: string;
            week_index: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            status: components["schemas"]["WeekStatus"];
            schedule: components["schemas"]["WeekDay"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        WeekStatus: "in_flight" | "completed" | "abandoned";
        WeekDay: {
            day_index: number;
            /** Format: date */
            date: string;
            type: components["schemas"]["DayType"];
            notes: string | null;
            completed: boolean;
            /** Format: date-time */
            completed_at: string | null;
            exercises: components["schemas"]["ExerciseLog"][];
        };
        ExerciseLog: {
            exercise_key: string;
            name: string;
            skipped: boolean;
            /** @enum {string|null} */
            feedback: "easy" | "hard" | "heavy" | "light" | null;
            prescribed: {
                series: number;
                reps: number;
                rest_time_sec: number;
                weight_lb: number | null;
                notes: string | null;
            };
            sets: components["schemas"]["PerformedSet"][];
        };
        PerformedSet: {
            performed_reps: number;
            performed_weight_lb: number | null;
        };
        WeekResponse: {
            week: components["schemas"]["Week"];
        };
        WeekListResponse: {
            weeks: components["schemas"]["Week"][];
        };
        SaveDayLog: {
            exercises: components["schemas"]["DayExerciseLog"][];
        };
        DayExerciseLog: {
            exercise_key: string;
            skipped: boolean;
            feedback: components["schemas"]["ExerciseFeedback"];
            sets: components["schemas"]["PerformedSet"][];
        };
        /** @enum {string|null} */
        ExerciseFeedback: "easy" | "hard" | "heavy" | "light" | null;
        UpdateDayLog: {
            completed: boolean;
            exercises: components["schemas"]["DayExerciseLog"][];
        };
        CompleteWeekStarted: {
            instanceId: string;
            details: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
