// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="../worker-configuration.d.ts" />

/**
 * Worker bindings. Auto-generated by `wrangler types` from wrangler.jsonc
 * (bindings) + .dev.vars (secrets). Regenerate after changing either via
 * `pnpm --filter @strengthsync/server types`.
 */
export type Env = Cloudflare.Env;
